### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by jerjorg** [msg-byu/bib#1]
Before lots of papers get placed in the master.bib file, I think we should agree upon naming conventions for authors, journals, publishers, dates, etc. It's also a good idea to agree upon the flags that should be required for each entry and whether or not we should remove the optional flags.

I would suggest that we use the ISO 4 abbreviation standard for journals. For example, Physical Review B abbreviated using this convention becomes Phys. Rev. B. and Nature Materials becomes Nat. Mater.

For authors we could spell out the first and last name but abbreviate the middle names. For example, Gus Lewis Warren Hart becomes Gus L. W. Hart and Wiley Spencer Morgan becomes Wiley S. Morgan. 

Months could be abbreviated using the first three letters (Jan, Feb, Mar, Apr, ...).

The required flags should at least include the title, authors, journal, volume, issue, pages, and year. We could include others such as month, publisher, doi, and url if they would be helpful.

**Comment by glwhart** [comment]
1. Do you have a list for the ISO 4 abbreviations? If so, add it to the repo maybe.
2. It would be nice to have a python script that checked each entry in the bib file and flagged any that had abbreviations that weren't in the ISO list

**Comment by wsmorgan** [comment]
@glwhart I thought we were going to assign the creation of such a script to an undergrad. If I recall we were all supposed to add our own bib files and then an undergrad was going to write a script that checked formatting of each entry and removed duplicates, and then wrote the actual master bib. Apparently we haven't been very on top of this....

**Comment by glwhart** [comment]
I don't think there's any reason to touch the author names. All bibstyle files I have ever used can figure out how to abbreviate from the full names.

**Comment by glwhart** [comment]
I think the convention that we settled on was that we were going to follow google scholar: LastNameYearFirstWordofTitle
